name: Medline Enterprise DevSecOps Organization CD

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: 'd0588ea1-2a87-4924-a8f5-2ad3c1db727f'

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with source code
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build JAVA Maven by maven build, clean
        run: |
            mvn clean package

       - name: Security- Run Prisma Cloud Scan
          id: prisma-cloud
          uses: bridgecrewio/checkov-action@master 
          env:
            PRISMA_API_URL: https://api3.prismacloud.io
          with:
            api-key: ${{ secrets.BC_API_KEY }}        

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Spring Enterprise 'Green' step with source code in the Enterprise plan
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: deploy
          service-name: 'enterprise-spring-apps'
          app-name: 'simple-ms'
          create-new-deployment: true
          deployment-name: 'green'
          use-staging-deployment: true
          package: ${{ env.ASC_PACKAGE_PATH }}/**/*.jar
          builder: 'default'

